### ISSUE TITLE
cson module misnamed?

### ISSUE THREAD

**Issue by oconnor663** [keybase/node-forge-sigchain#1]
When I run main.js on master, I get:

```
module.js:338
    throw err;
          ^
Error: Cannot find module 'CSON'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/jacko/node-forge-sigchain/lib/main.js:10:10)
    at Object.<anonymous> (/home/jacko/node-forge-sigchain/lib/main.js:388:4)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
```

This fixes it: https://github.com/keybase/node-forge-sigchain/commit/8ee2dcdde99e1137c41a8bfd9454b95cb512b3f0

Maybe one of us has an unusual node config on our machine?

**Comment by oconnor663** [comment]
I put that commit on a branch, but let me know if I should go ahead and land it.
